config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    validates :name, presence: true, length: { maximum: 50}
    validates :email, presence: true, length: { maximum: 255}, 
                      format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
                      uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%> | Ruby on Rails Tutorial Sample App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <nav>
  <ul>
  <li><%= link_to "Home", static_pages_home_url%></li>
  <li><%= link_to "Help", static_pages_help_url%></li>
  <li><%= link_to "About", static_pages_about_url%></li>
  </ul>
  </nav>
  </header>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home")%>
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

<%=link_to "Sign Up Now!", "#"%>
<%# <%=link_to image_tag("cat.jpeg", alt:"rails logo"), "https://www.google.com/search?q=cat&tbm=isch&ved=2ahUKEwjGiM3bkp30AhWUBjQIHaYuDpsQ2-cCegQIABAA"%> %>